# Day 2 - Input & Variables
print("What is your name?")
myName = input("Your Name: ")
print()
print("What is your favourite food?")
myFood = input("Your favourite food: ")
print()
print("What is your favourite music?")
myMusic = input("Your favourite music: ")
print()
print("Where do you live?")
myLocation = input("Your location: ")
print()
print("You are " + myName + " and you want to eat " + myFood + " and you want to listen to " + myMusic + " and you live in " + myLocation + ".")
