# Day 3 - Concatenation
print("=== Ultimate Wacky Recipe Maker ===")
print("""Build an amazing dish for today's evening meal!""")
print()
food = input("Name a food: ")
plant = input("Name a type of plant: ")
cooking = input("Name a method of cooking: ")
burned = input("What word describes burned food: ")
item = input("name a DIY item: ")
print()
print("== Menu ==")
print("Today's evening meal is", cooking, food, "with", burned, plant, "on a bed of", item)
